import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AreaChart, BrainCircuit, Check, FlaskConical, Layers3, Pause, Play, Plus, Save, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { evolutionApi } from "../../shared/services/evolution";
import { marketDataApi } from "../../shared/services/marketData";
import { datasetStartDate } from "../../shared/lib/datasetDates";
import { dynamicParametersApi } from "../../shared/services/dynamicParameters";
import { robustnessApi, type ParameterDefinition, type ParameterSpace, type RobustnessMetric } from "../../shared/services/robustness";
import { parameterResearchApi, type Candidate, type ResearchAnalysis, type ResearchConfiguration, type ResearchPlan, type ResearchPoint, type StagePlanInput, type SurrogateProposal } from "../../shared/services/parameterResearch";
import { Button } from "../../shared/ui/Button";
import { Card, CardDescription, CardHeader, CardTitle } from "../../shared/ui/Card";
import { ComputePlanSummary, ComputeProgress, ComputeStatusBadge } from "../computetasks/ComputeTaskComponents";

const inputClass="min-h-10 w-full rounded-lg border border-white/10 bg-slate-950/70 px-3 text-sm text-slate-200 outline-none focus:border-teal-400/50";
const active=new Set(["planned","queued","running","partial"]);
const metricLabels:Record<RobustnessMetric,string>={log_final_nav_ratio:"log 期末淨值比",drawdown_residual_ratio:"最大回撤殘值比",log_drawdown_residual_ratio:"log 最大回撤殘值比",performance_drawdown_composite:"績效回撤綜合指標",qualification:"合格狀態"};
const analysisLabels:Record<string,string>={G:"報酬分析",H:"對照測試",L:"擾動行情",C:"行情樣貌反推"};
type Variable={name:string;label:string;type:"float"|"int";legal_min:number;legal_max:number;default_step:number;active:boolean};
function dayStart(value:string){return value?new Date(`${value}T00:00:00`).getTime():0}function dayEnd(value:string){return value?new Date(`${value}T23:59:59.999`).getTime():0}
function dateValue(date:Date){return date.toISOString().slice(0,10)}
function unique(values:number[]){return [...new Set(values.map(value=>Number(value.toFixed(8))))].sort((a,b)=>a-b)}
function buildSpace(variables:Variable[],base:Record<string,number>,selected:string[],radius:number){
 const axes=selected.map(name=>{const item=variables.find(v=>v.name===name)!;const center=base[name];const step=item.type==="int"?Math.max(1,Math.round(item.default_step)):item.default_step;const values=unique(Array.from({length:radius*2+1},(_,i)=>center+(i-radius)*step).map(v=>item.type==="int"?Math.round(v):v).filter(v=>v>=item.legal_min-1e-9&&v<=item.legal_max+1e-9));return {...item,values,step,study_start:0,study_end:values.length-1}});
 const fixed=Object.fromEntries(Object.entries(base).filter(([name])=>!selected.includes(name)));const coordinates=axes.map(axis=>axis.values.reduce((best,value,index)=>Math.abs(value-base[axis.name])<Math.abs(axis.values[best]-base[axis.name])?index:best,0));
 return {space:{schema_version:"p08-grid-v1",axes,fixed} as ParameterSpace,coordinates};
}
function useVisible(){const[visible,setVisible]=useState(document.visibilityState==="visible");useEffect(()=>{const update=()=>setVisible(document.visibilityState==="visible");document.addEventListener("visibilitychange",update);return()=>document.removeEventListener("visibilitychange",update)},[]);return visible}

export function ParameterResearchPage(){
 const qc=useQueryClient(),visible=useVisible();const linkedCandidateID=Number(new URLSearchParams(location.search).get("candidate"));const linkedCandidateQ=useQuery({queryKey:["parameter-research-candidate",linkedCandidateID],queryFn:()=>parameterResearchApi.getCandidate(linkedCandidateID),enabled:linkedCandidateID>0});const genomesQ=useQuery({queryKey:["genomes"],queryFn:evolutionApi.listGenomes});const instrumentsQ=useQuery({queryKey:["market-data-instruments"],queryFn:marketDataApi.instruments});const dynamicQ=useQuery({queryKey:["dynamic-studies"],queryFn:()=>dynamicParametersApi.list(100)});const configurationsQ=useQuery({queryKey:["parameter-research-configurations"],queryFn:parameterResearchApi.listConfigurations});
 const genomes=genomesQ.data??[],instruments=instrumentsQ.data?.instruments??[],dynamicStudies=(dynamicQ.data??[]).filter(item=>item.policy_artifact_id&&item.artifact_set_hash);
 const[genomeId,setGenomeId]=useState(0),[instrumentId,setInstrumentId]=useState(""),[mode,setMode]=useState<"static"|"dynamic">("static"),[dynamicStudyId,setDynamicStudyId]=useState(0),[axes,setAxes]=useState<string[]>([]),[radius,setRadius]=useState(3),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(()=>dateValue(new Date(Date.now()-86400000))),[executionMode,setExecutionMode]=useState("close_next_open"),[name,setName]=useState("參數績效地形研究");
 const[selectedConfiguration,setSelectedConfiguration]=useState(0),[runId,setRunId]=useState(0),[plan,setPlan]=useState<ResearchPlan>(),[stageInput,setStageInput]=useState<StagePlanInput>(),[analysis,setAnalysis]=useState<ResearchAnalysis>(),[metric,setMetric]=useState<RobustnessMetric>("log_final_nav_ratio"),[selectedPoint,setSelectedPoint]=useState(0),[seriesIds,setSeriesIds]=useState<number[]>([]),[surrogatePlan,setSurrogatePlan]=useState<any>(),[surrogateId,setSurrogateId]=useState(0);
 useEffect(()=>{if(!genomeId&&genomes.length)setGenomeId(genomes[0].id)},[genomeId,genomes]);useEffect(()=>{if(!instrumentId&&instruments.length)setInstrumentId(instruments[0].id)},[instrumentId,instruments]);useEffect(()=>{if(linkedCandidateQ.data)setSelectedConfiguration(linkedCandidateQ.data.configuration_id);else if(!selectedConfiguration&&configurationsQ.data?.length)setSelectedConfiguration(configurationsQ.data[0].id)},[linkedCandidateQ.data,selectedConfiguration,configurationsQ.data]);useEffect(()=>{if(!dynamicStudyId&&dynamicStudies.length)setDynamicStudyId(dynamicStudies[0].id)},[dynamicStudyId,dynamicStudies]);
 const paramsQ=useQuery({queryKey:["robustness-parameters",genomeId],queryFn:()=>robustnessApi.parameters(genomeId),enabled:genomeId>0});const selectedDynamic=dynamicStudies.find(item=>item.id===dynamicStudyId);const dynamicSpaceQ=useQuery({queryKey:["dynamic-policy-space",selectedDynamic?.policy_artifact_id],queryFn:()=>parameterResearchApi.dynamicSpace(selectedDynamic!.policy_artifact_id!),enabled:mode==="dynamic"&&!!selectedDynamic?.policy_artifact_id});
 const staticVariables=(paramsQ.data?.definitions??[]).filter(item=>item.active);const variables:Variable[]=mode==="static"?staticVariables:((dynamicSpaceQ.data?.schema.variables??[]).map(item=>({name:item.stable_id,label:`${item.parameter_id} · ${item.role}${item.prediction_input?` · ${item.prediction_input}`:""}`,type:"float" as const,legal_min:item.lower,legal_max:item.upper,default_step:item.minimum_step,active:true})));const base=mode==="static"?(paramsQ.data?.values??{}):(dynamicSpaceQ.data?.base_values??{});
 useEffect(()=>{const valid=axes.filter(name=>variables.some(item=>item.name===name));if(valid.length===0&&variables.length)setAxes(variables.slice(0,Math.min(2,variables.length)).map(item=>item.name));else if(valid.length!==axes.length)setAxes(valid)},[mode,variables.map(item=>item.name).join("|")]);
 const built=useMemo(()=>buildSpace(variables,base,axes,radius),[variables,base,axes,radius]);const instrument=instruments.find(item=>item.id===instrumentId);const researchInterval=instrument?.supported_intervals?.[0]??"1d";const selectedDatasetStart=datasetStartDate(instrument,researchInterval);useEffect(()=>{if(selectedDatasetStart)setStartDate(selectedDatasetStart)},[selectedDatasetStart]);const configurationInput={name,notes:"",tags:[mode==="dynamic"?"動態政策":"固定參數"],genome_id:genomeId,parameter_space:built.space,base_coordinates:built.coordinates,backtest:{instrument_id:instrumentId,data_source:instrument?.data_source,symbol:instrument?.symbol??instrumentId,interval:researchInterval,execution_mode:executionMode,start_time_ms:dayStart(startDate),end_time_ms:dayEnd(endDate),long_term_filter_enabled:true,long_term_filter_months:10},dynamic:mode==="dynamic"&&dynamicSpaceQ.data?{study_id:dynamicSpaceQ.data.study_id,policy_artifact_id:dynamicSpaceQ.data.policy_artifact_id}:undefined};
 const createConfig=useMutation({mutationFn:()=>parameterResearchApi.createConfiguration(configurationInput),onSuccess:value=>{setSelectedConfiguration(value.id);qc.invalidateQueries({queryKey:["parameter-research-configurations"]})}});const runsQ=useQuery({queryKey:["parameter-research-runs",selectedConfiguration],queryFn:()=>parameterResearchApi.listRuns(selectedConfiguration),enabled:selectedConfiguration>0});useEffect(()=>{if(runId===0&&runsQ.data?.length)setRunId(runsQ.data[0].id)},[runId,runsQ.data]);const planRun=useMutation({mutationFn:()=>parameterResearchApi.planRun(selectedConfiguration),onSuccess:value=>{setPlan(value);setStageInput(undefined)}});const startRun=useMutation({mutationFn:()=>parameterResearchApi.startRun(selectedConfiguration,plan!),onSuccess:value=>{setRunId(value.id);setPlan(undefined);qc.invalidateQueries({queryKey:["parameter-research-runs",selectedConfiguration]})}});const runQ=useQuery({queryKey:["parameter-research-run",runId],queryFn:()=>parameterResearchApi.getRun(runId),enabled:runId>0,refetchInterval:q=>visible&&active.has((q.state.data as any)?.status??"")?1500:false});const run=runQ.data;
 const appendPlan=useMutation({mutationFn:()=>parameterResearchApi.planStage(runId,{kind:"append_global"}),onSuccess:value=>{setPlan(value);setStageInput({kind:"append_global"})}});const refinePlan=useMutation({mutationFn:()=>parameterResearchApi.planStage(runId,{kind:"local_refinement",center_point_id:selectedPoint,radius}),onSuccess:value=>{setPlan(value);setStageInput({kind:"local_refinement",center_point_id:selectedPoint,radius})}});const startStage=useMutation({mutationFn:()=>parameterResearchApi.startStage(runId,stageInput!,plan!),onSuccess:()=>{setPlan(undefined);setStageInput(undefined);qc.invalidateQueries({queryKey:["parameter-research-run",runId]});if(surrogateId)qc.invalidateQueries({queryKey:["parameter-research-proposals",surrogateId]})}});const analyze=useMutation({mutationFn:()=>parameterResearchApi.analyze(runId,metric),onSuccess:setAnalysis});const derive=useMutation({mutationFn:()=>parameterResearchApi.deriveCandidates(analysis!.id),onSuccess:()=>qc.invalidateQueries({queryKey:["parameter-research-candidates",selectedConfiguration]})});const candidatesQ=useQuery({queryKey:["parameter-research-candidates",selectedConfiguration],queryFn:()=>parameterResearchApi.listCandidates(selectedConfiguration),enabled:selectedConfiguration>0});useEffect(()=>{if(linkedCandidateID&&(candidatesQ.data??[]).some(item=>item.id===linkedCandidateID))document.getElementById(`candidate-${linkedCandidateID}`)?.scrollIntoView({block:"center"})},[linkedCandidateID,candidatesQ.data]);const candidateAction=useMutation({mutationFn:({candidate,action}:{candidate:Candidate;action:"export"|"promote"})=>action==="export"?parameterResearchApi.exportCandidate(candidate.id):parameterResearchApi.promoteCandidate(candidate.id),onSuccess:()=>qc.invalidateQueries({queryKey:["parameter-research-candidates",selectedConfiguration]})});const series=useMutation({mutationFn:()=>parameterResearchApi.createSeries("研究設定比較",seriesIds)});
 const surrogatesQ=useQuery({queryKey:["parameter-research-surrogates",runId],queryFn:()=>parameterResearchApi.listSurrogates(runId),enabled:runId>0});useEffect(()=>{setSurrogateId(surrogatesQ.data?.[0]?.id??0)},[runId,surrogatesQ.data?.[0]?.id]);const planSurrogate=useMutation({mutationFn:()=>parameterResearchApi.planSurrogate(runId),onSuccess:setSurrogatePlan});const startSurrogate=useMutation({mutationFn:()=>parameterResearchApi.startSurrogate(runId,surrogatePlan),onSuccess:value=>{setSurrogateId(value.id);setSurrogatePlan(undefined);qc.invalidateQueries({queryKey:["parameter-research-surrogates",runId]})}});const surrogateQ=useQuery({queryKey:["parameter-research-surrogate",surrogateId],queryFn:()=>parameterResearchApi.getSurrogate(surrogateId),enabled:surrogateId>0,refetchInterval:q=>visible&&active.has((q.state.data as any)?.status??"")?1500:false});const proposalsQ=useQuery({queryKey:["parameter-research-proposals",surrogateId],queryFn:()=>parameterResearchApi.listProposals(surrogateId),enabled:surrogateId>0&&surrogateQ.data?.status==="completed"});const createProposal=useMutation({mutationFn:(kind:"high_return"|"low_drawdown"|"high_uncertainty"|"pure_coverage")=>parameterResearchApi.createProposals(surrogateId,kind),onSuccess:()=>qc.invalidateQueries({queryKey:["parameter-research-proposals",surrogateId]})});const proposalStage=useMutation({mutationFn:()=>{const ids=(proposalsQ.data??[]).filter(item=>!item.actual_point_id).map(item=>item.id);return parameterResearchApi.planStage(runId,{kind:"surrogate_proposals",surrogate_id:surrogateId,proposal_ids:ids})},onSuccess:value=>{const ids=(proposalsQ.data??[]).filter(item=>!item.actual_point_id).map(item=>item.id);setPlan(value);setStageInput({kind:"surrogate_proposals",surrogate_id:surrogateId,proposal_ids:ids})}});
 const selectedConfig=configurationsQ.data?.find(item=>item.id===selectedConfiguration);const points=run?.points??[];
 return <section className="space-y-5">
  <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-100"><Layers3 className="h-6 w-6 text-teal-300"/>參數績效地形研究</h1><p className="mt-1 max-w-4xl text-sm leading-6 text-slate-400">以不可變設定完成全域探索、有限細化、穩健區域與多候選管理。任何大量計算都先顯示固定清單；代理點與未知點不會成為正式證據。</p></div>{!visible&&<span className="rounded-full border border-amber-500/20 bg-amber-500/10 px-3 py-1 text-xs text-amber-300">背景頁面已停止輪詢</span>}</header>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(340px,.85fr)]">
   <Card><CardHeader><div><CardTitle>1. 建立不可變研究設定</CardTitle><CardDescription>結構設定、研究常數與研究變數分開保存；建立後只能複製成新設定。</CardDescription></div></CardHeader><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
    <Field label="名稱"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="研究結構"><select className={inputClass} value={mode} onChange={e=>setMode(e.target.value as any)}><option value="static">固定核心參數</option><option value="dynamic">預測與動態政策</option></select></Field><Field label="來源參數"><select className={inputClass} value={genomeId} onChange={e=>setGenomeId(Number(e.target.value))}>{genomes.map(item=><option key={item.id} value={item.id}>#{item.id} · {item.name||item.role}</option>)}</select></Field>
    {mode==="dynamic"&&<Field label="凍結模型與政策"><select className={inputClass} value={dynamicStudyId} onChange={e=>setDynamicStudyId(Number(e.target.value))}>{dynamicStudies.map(item=><option key={item.id} value={item.id}>#{item.id} · {item.name}</option>)}</select></Field>}<Field label="標的"><select className={inputClass} value={instrumentId} onChange={e=>setInstrumentId(e.target.value)}>{instruments.map(item=><option key={item.id} value={item.id}>{item.display_name}</option>)}</select></Field><Field label="執行時點"><select className={inputClass} value={executionMode} onChange={e=>setExecutionMode(e.target.value)}><option value="close_next_open">收盤判斷、次日開盤執行</option><option value="close_same_bar">收盤判斷、同日收盤執行</option></select></Field><Field label="開始日期"><input className={inputClass} type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></Field><Field label="結束日期"><input className={inputClass} type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></Field><Field label="研究半徑（格）"><input className={inputClass} type="number" min={1} max={20} value={radius} onChange={e=>setRadius(Number(e.target.value))}/></Field>
   </div><div className="mt-4"><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">研究變數（其餘為研究常數）</div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{variables.map(item=><label key={item.name} className={`flex cursor-pointer items-center gap-2 rounded-lg border p-3 text-sm ${axes.includes(item.name)?"border-teal-400/30 bg-teal-400/10 text-teal-100":"border-white/5 text-slate-400"}`}><input type="checkbox" checked={axes.includes(item.name)} onChange={()=>setAxes(current=>current.includes(item.name)?current.filter(v=>v!==item.name):[...current,item.name].slice(-8))}/><span className="truncate">{item.label}</span><span className="ml-auto text-xs">{base[item.name]?.toFixed(item.type==="int"?0:2)}</span></label>)}</div></div><div className="mt-4 flex flex-wrap items-center gap-2"><Button icon={Save} loading={createConfig.isPending} disabled={!genomeId||!instrumentId||axes.length===0||built.space.axes.some(axis=>axis.values.length===0)||configurationInput.backtest.end_time_ms<=configurationInput.backtest.start_time_ms} onClick={()=>createConfig.mutate()}>保存不可變設定</Button><span className="text-xs text-slate-500">{axes.length} 維 · 理論 {built.space.axes.reduce((total,axis)=>total*axis.values.length,1).toLocaleString()} 組</span></div>{createConfig.error&&<ErrorText error={createConfig.error}/>}</Card>
   <Card><CardHeader><div><CardTitle>研究設定</CardTitle><CardDescription>固定內容 hash；封存不刪除研究證據。</CardDescription></div></CardHeader><div className="max-h-[460px] space-y-2 overflow-auto">{(configurationsQ.data??[]).map(item=><button key={item.id} className={`w-full rounded-lg border p-3 text-left ${selectedConfiguration===item.id?"border-teal-400/30 bg-teal-400/10":"border-white/5 bg-white/[.02]"}`} onClick={()=>{setSelectedConfiguration(item.id);setRunId(0);setAnalysis(undefined);setPlan(undefined)}}><div className="flex items-center justify-between gap-2"><span className="font-medium text-slate-200">{item.name}</span><span className="text-xs text-slate-500">#{item.id}</span></div><div className="mt-1 text-xs text-slate-400">{item.dynamic_mode?"動態政策":"固定參數"} · {item.parameter_space.axes.length} 維 · {item.instrument_id} · {item.interval}</div><div className="mt-1 truncate font-mono text-[10px] text-slate-600">{item.config_hash}</div></button>)}</div></Card>
  </div>
  {selectedConfig&&<Card><CardHeader><div><CardTitle>2. 計算階段</CardTitle><CardDescription>基準點、軸向邊界與 Sobol／完整枚舉先形成精確清單；每次追加或細化都是新的有限階段。</CardDescription></div></CardHeader>{(runsQ.data?.length??0)>0&&<div className="mb-3 max-w-md"><Field label="重新開啟既有研究"><select className={inputClass} value={runId} onChange={e=>{setRunId(Number(e.target.value));setAnalysis(undefined);setPlan(undefined)}}>{runsQ.data!.map(item=><option key={item.id} value={item.id}>#{item.id} · {item.status} · {new Date(item.created_at).toLocaleString()}</option>)}</select></Field></div>}<div className="flex flex-wrap gap-2"><Button variant="secondary" icon={FlaskConical} loading={planRun.isPending} onClick={()=>planRun.mutate()}>預覽第一批</Button>{runId>0&&<><Button variant="secondary" icon={Plus} loading={appendPlan.isPending} onClick={()=>appendPlan.mutate()}>預覽追加批次</Button><Button variant="secondary" icon={AreaChart} loading={refinePlan.isPending} disabled={!selectedPoint} onClick={()=>refinePlan.mutate()}>預覽局部細化</Button><Button variant="ghost" icon={Pause} onClick={()=>parameterResearchApi.pauseRun(runId)}>暫停</Button></>}</div>{plan&&<div className="mt-4 space-y-3"><ComputePlanSummary preview={plan.compute}/><div className="grid gap-2 text-xs text-slate-400 sm:grid-cols-4"><Stat label="取樣模式" value={plan.global?.mode??plan.stage_type}/><Stat label="唯一點" value={plan.points.length}/><Stat label="快取命中" value={plan.compute.cache_hit_count}/><Stat label="下一索引" value={plan.next_sobol_index}/></div><Button icon={Play} loading={startRun.isPending||startStage.isPending} onClick={()=>runId&&stageInput?startStage.mutate():startRun.mutate()}>確認並啟動</Button></div>}{run&&<div className="mt-5 space-y-3"><div className="flex items-center gap-3"><ComputeStatusBadge status={run.status}/><span className="text-sm text-slate-300">{run.global_unique_point_count} 個全域實測點 · {run.global_batch_count} 批 · 下一 Sobol {run.next_sobol_index}</span></div>{run.stages.map(stage=><div key={stage.id} className="rounded-lg border border-white/5 bg-slate-950/40 p-3"><div className="mb-2 flex items-center justify-between text-sm"><span>{stage.ordinal+1}. {stage.stage_type}</span><ComputeStatusBadge status={stage.status}/></div><ComputeProgress task={{id:stage.compute_task_id??0,status:stage.status,progress:stage.unique_count?stage.completed_count/stage.unique_count:0,total_items:stage.unique_count,valid_result_count:stage.completed_count,failed_count:stage.failed_count,missing_count:stage.missing_count} as any}/></div>)}</div>}</Card>}
  {run&&<Card><CardHeader><div><CardTitle>代理模型探索（選用）</CardTitle><CardDescription>至少完成兩批初始 Sobol 實測後才可訓練；OOF 未勝過基準時，相應提案會被禁止。所有提案仍須送入下一個真實回測階段。</CardDescription></div></CardHeader><div className="flex flex-wrap gap-2"><Button variant="secondary" icon={BrainCircuit} loading={planSurrogate.isPending} onClick={()=>planSurrogate.mutate()}>預覽代理模型</Button>{surrogatePlan&&<Button icon={Play} loading={startSurrogate.isPending} onClick={()=>startSurrogate.mutate()}>確認訓練</Button>}</div>{surrogatePlan&&<div className="mt-3"><ComputePlanSummary preview={surrogatePlan}/></div>}{surrogateQ.data&&<div className="mt-4 space-y-3"><div className="flex flex-wrap items-center gap-3"><ComputeStatusBadge status={surrogateQ.data.status}/><span className="text-xs text-slate-400">報酬引導：{surrogateQ.data.can_guide_return?"可用":"禁用"} · 回撤引導：{surrogateQ.data.can_guide_drawdown?"可用":"禁用"}</span></div>{surrogateQ.data.status==="completed"&&<><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" loading={createProposal.isPending} disabled={!surrogateQ.data.can_guide_return} onClick={()=>createProposal.mutate("high_return")}>高報酬</Button><Button size="sm" variant="secondary" loading={createProposal.isPending} disabled={!surrogateQ.data.can_guide_drawdown} onClick={()=>createProposal.mutate("low_drawdown")}>低回撤</Button><Button size="sm" variant="secondary" loading={createProposal.isPending} onClick={()=>createProposal.mutate("high_uncertainty")}>高不確定</Button><Button size="sm" variant="secondary" loading={createProposal.isPending} onClick={()=>createProposal.mutate("pure_coverage")}>純覆蓋</Button></div><ProposalList proposals={proposalsQ.data??[]}/><Button icon={FlaskConical} loading={proposalStage.isPending} disabled={!(proposalsQ.data??[]).some(item=>!item.actual_point_id)} onClick={()=>proposalStage.mutate()}>預覽提案真實回測</Button></>}</div>}{(planSurrogate.error||startSurrogate.error||createProposal.error||proposalStage.error)&&<ErrorText error={planSurrogate.error||startSurrogate.error||createProposal.error||proposalStage.error}/>}</Card>}
  {run&&<div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(340px,.75fr)]"><Card><CardHeader><div><CardTitle>3. 實測地形</CardTitle><CardDescription>未知、未完成與代理點不插值；切換指標只讀已保存結果。</CardDescription></div></CardHeader><div className="mb-3 flex flex-wrap gap-2"><select className={`${inputClass} max-w-xs`} value={metric} onChange={e=>setMetric(e.target.value as RobustnessMetric)}>{Object.entries(metricLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><Button variant="secondary" icon={ShieldCheck} loading={analyze.isPending} disabled={!points.some(point=>point.status==="completed")} onClick={()=>analyze.mutate()}>建立 J 分析快照</Button>{analysis&&<Button icon={Check} loading={derive.isPending} onClick={()=>derive.mutate()}>產生角色候選</Button>}</div><Landscape points={points} axes={selectedConfig?.parameter_space.axes.map(axis=>axis.name)??[]} metric={metric} selected={selectedPoint} onSelect={setSelectedPoint}/>{analysis&&<div className="mt-3 grid gap-2 sm:grid-cols-3"><Stat label="合格連通區域" value={analysis.result.regions.length}/><Stat label="候選提案" value={analysis.result.regions.reduce((sum,r)=>sum+r.proposals.length,0)}/><Stat label="未知格點" value={analysis.result.missing_coordinates.length}/></div>}</Card><Card><CardHeader><div><CardTitle>評估點</CardTitle><CardDescription>選取實測點後可建立手動候選或局部細化。</CardDescription></div></CardHeader><div className="max-h-[500px] space-y-2 overflow-auto">{points.map(point=><button key={point.id} onClick={()=>setSelectedPoint(point.id)} className={`w-full rounded-lg border p-3 text-left ${selectedPoint===point.id?"border-teal-400/30 bg-teal-400/10":"border-white/5"}`}><div className="flex justify-between gap-2"><span className={point.qualified?"text-teal-300":"text-rose-300"}>{point.qualified?"合格":"未合格"} · #{point.id}</span><span className="text-xs text-slate-500">{point.coordinates.join(" · ")}</span></div><div className="mt-1 text-xs text-slate-400">{formatMetric(metricValue(point,metric))}</div></button>)}</div>{selectedPoint>0&&<Button className="mt-3" variant="secondary" onClick={()=>parameterResearchApi.manualCandidate(selectedPoint).then(()=>qc.invalidateQueries({queryKey:["parameter-research-candidates",selectedConfiguration]}))}>存為手動候選</Button>}</Card></div>}
  <Card><CardHeader><div><CardTitle>4. 穩健候選與人工採用</CardTitle><CardDescription>候選不會自動採用；G／H／L／C 僅保存各自七種狀態，不形成系統及格線。</CardDescription></div></CardHeader><div className="grid gap-3 lg:grid-cols-2 2xl:grid-cols-3">{(candidatesQ.data??[]).map(candidate=><CandidateCard key={candidate.id} candidate={candidate} focused={candidate.id===linkedCandidateID} busy={candidateAction.isPending} onAction={action=>candidateAction.mutate({candidate,action})}/>)}</div></Card>
  <Card><CardHeader><div><CardTitle>5. 研究系列</CardTitle><CardDescription>不同設定仍維持各自地形；系統依共同背景與點集合判定配對、未配對、描述或不相容。</CardDescription></div></CardHeader><div className="flex flex-wrap gap-2">{(configurationsQ.data??[]).map(item=><label key={item.id} className="flex items-center gap-2 rounded-lg border border-white/5 px-3 py-2 text-sm text-slate-300"><input type="checkbox" checked={seriesIds.includes(item.id)} onChange={()=>setSeriesIds(current=>current.includes(item.id)?current.filter(id=>id!==item.id):[...current,item.id])}/>{item.name}</label>)}</div><Button className="mt-3" icon={Layers3} disabled={seriesIds.length<2} loading={series.isPending} onClick={()=>series.mutate()}>建立版本化比較快照</Button>{series.data&&<pre className="mt-3 overflow-auto rounded-lg bg-slate-950/70 p-3 text-xs text-slate-400">{JSON.stringify(series.data,null,2)}</pre>}</Card>
 </section>
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1"><span className="text-xs font-medium text-slate-400">{label}</span>{children}</label>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-lg border border-white/5 bg-white/[.02] p-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 font-semibold text-slate-200">{value}</div></div>}
function ErrorText({error}:{error:unknown}){return <p className="mt-3 text-sm text-rose-300">{error instanceof Error?error.message:"操作失敗"}</p>}
function metricValue(point:ResearchPoint,metric:RobustnessMetric){if(!point.metrics)return undefined;return metric==="qualification"?(point.metrics.qualified?1:0):point.metrics[metric]}
function formatMetric(value:number|undefined){return value===undefined||!Number.isFinite(value)?"未知":value.toFixed(4)}
function Landscape({points,axes,metric,selected,onSelect}:{points:ResearchPoint[];axes:string[];metric:RobustnessMetric;selected:number;onSelect:(id:number)=>void}){const completed=points.filter(point=>point.metrics);if(!completed.length)return <div className="flex h-64 items-center justify-center rounded-lg border border-dashed border-white/10 text-sm text-slate-500">尚無實測點</div>;const xValues=[...new Set(completed.map(p=>p.coordinates[0]))].sort((a,b)=>a-b),yValues=[...new Set(completed.map(p=>p.coordinates[1]??0))].sort((a,b)=>a-b);const values=completed.map(p=>metricValue(p,metric)??0),minimum=Math.min(...values),maximum=Math.max(...values);return <div className="overflow-auto rounded-lg border border-white/5 bg-slate-950/60 p-3"><div className="mb-2 text-xs text-slate-500">X：{axes[0]??"參數"}{axes[1]?` · Y：${axes[1]}`:" · 一維切片"}</div><div className="grid min-w-[420px] gap-1" style={{gridTemplateColumns:`repeat(${xValues.length},minmax(32px,1fr))`}}>{yValues.flatMap(y=>xValues.map(x=>{const point=completed.find(p=>p.coordinates[0]===x&&(p.coordinates[1]??0)===y);if(!point)return <div key={`${x}-${y}`} className="aspect-square rounded bg-slate-900/70"/>;const value=metricValue(point,metric)??0,ratio=maximum===minimum?.5:(value-minimum)/(maximum-minimum);return <button key={`${x}-${y}`} title={`${formatMetric(value)} · ${JSON.stringify(point.parameters)}`} onClick={()=>onSelect(point.id)} className={`aspect-square rounded border transition-none ${selected===point.id?"border-white":"border-transparent"}`} style={{backgroundColor:point.qualified?`rgba(45,212,191,${.18+.72*ratio})`:`rgba(251,113,133,${.18+.62*(1-ratio)})`}}/>}))}</div></div>}
function CandidateCard({candidate,focused,busy,onAction}:{candidate:Candidate;focused:boolean;busy:boolean;onAction:(action:"export"|"promote")=>void}){return <div id={`candidate-${candidate.id}`} className={`rounded-xl border bg-slate-950/45 p-4 ${focused?"border-amber-300/60 ring-2 ring-amber-300/20":"border-white/5"}`}><div className="flex items-start justify-between gap-2"><div><div className="font-medium text-slate-200">候選 #{candidate.id}</div><div className="mt-1 flex flex-wrap gap-1">{candidate.roles.map(role=><span key={role} className="rounded bg-teal-400/10 px-2 py-0.5 text-[10px] text-teal-300">{role}</span>)}</div></div><span className="text-xs text-slate-500">{candidate.completeness}</span></div><div className="mt-3 grid grid-cols-2 gap-2">{candidate.analysis_links.map(link=><div key={link.kind} className="rounded border border-white/5 p-2 text-xs"><span className="text-slate-400">{analysisLabels[link.kind]}</span><div className="mt-1 text-slate-200">{link.status}</div></div>)}</div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="secondary" disabled={busy||!!candidate.gene_record_id} onClick={()=>onAction("export")}>{candidate.gene_record_id?`參數庫 #${candidate.gene_record_id}`:"存入參數庫"}</Button><Button size="sm" disabled={busy} onClick={()=>onAction("promote")}>設為已採用參數</Button><Link className="inline-flex min-h-8 items-center rounded-lg border border-teal-400/20 bg-teal-400/10 px-3 py-1 text-xs font-semibold text-teal-200 hover:bg-teal-400/20" to={`/generator?mode=perturbation&candidate=${candidate.id}`}>開啟 L 擾動測試</Link><Link className="inline-flex min-h-8 items-center rounded-lg border border-white/10 bg-white/[0.04] px-3 py-1 text-xs font-semibold text-slate-200 hover:bg-white/[0.08]" to={`/control-analysis?candidate=${candidate.id}`}>開啟 H 對照</Link><Link className="inline-flex min-h-8 items-center rounded-lg border border-teal-400/20 bg-teal-400/10 px-3 py-1 text-xs font-semibold text-teal-200 hover:bg-teal-400/20" to={`/kline-inverse?candidate=${candidate.id}`}>建立 C 草稿</Link></div></div>}
function ProposalList({proposals}:{proposals:SurrogateProposal[]}){if(!proposals.length)return null;return <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{proposals.map(item=><div key={item.id} className="rounded-lg border border-white/5 bg-slate-950/45 p-3 text-xs"><div className="flex justify-between gap-2 text-slate-300"><span>提案 #{item.id}</span><span className={item.actual_point_id?"text-teal-300":"text-amber-300"}>{item.actual_point_id?`已實測 #${item.actual_point_id}`:"待實測"}</span></div><div className="mt-1 text-slate-500">{item.types.join(" · ")}</div><div className="mt-2 text-slate-400">報酬 {formatMetric(item.prediction.return_mean)} · 回撤 {formatMetric(item.prediction.drawdown_mean)}</div></div>)}</div>}
