import { useMemo, useState } from "react";
import { Check, Pin, Search, X } from "lucide-react";
import type { GenomeRecord } from "../services/evolution";
import { Button } from "./Button";

type Props = { genomes: GenomeRecord[]; value: number; onChange: (id: number) => void; label?: string; disabled?: boolean };
type Preferences = { pinned: number[]; recent: number[] };
const key = "quantsaas.parameter-picker.v1";
function role(value: string) { return value === "champion" ? "已採用" : value === "retired" ? "歷史" : "候選"; }
function load(): Preferences { try { const value = JSON.parse(localStorage.getItem(key) ?? "{}"); return { pinned: Array.isArray(value.pinned) ? value.pinned : [], recent: Array.isArray(value.recent) ? value.recent : [] }; } catch { return { pinned: [], recent: [] }; } }

export function ParameterPicker({ genomes, value, onChange, label = "參數來源", disabled }: Props) {
  const [open, setOpen] = useState(false), [query, setQuery] = useState(""), [prefs, setPrefs] = useState(load);
  const selected = genomes.find((item) => item.id === value);
  const matches = useMemo(() => { const text = query.trim().toLowerCase(); return genomes.filter((item) => !text || [item.id, item.name ?? "", item.role, item.instrument_id ?? "", item.interval ?? ""].join(" ").toLowerCase().includes(text)); }, [genomes, query]);
  const byId = new Map(matches.map((item) => [item.id, item]));
  const pinned = prefs.pinned.map((id) => byId.get(id)).filter((item): item is GenomeRecord => Boolean(item));
  const recent = prefs.recent.filter((id) => !prefs.pinned.includes(id)).map((id) => byId.get(id)).filter((item): item is GenomeRecord => Boolean(item));
  const others = matches.filter((item) => !prefs.pinned.includes(item.id) && !prefs.recent.includes(item.id));
  function update(next: Preferences) { setPrefs(next); localStorage.setItem(key, JSON.stringify(next)); }
  function choose(item: GenomeRecord) { update({ ...prefs, recent: [item.id, ...prefs.recent.filter((id) => id !== item.id)].slice(0, 12) }); onChange(item.id); setOpen(false); }
  function toggle(id: number) { update({ ...prefs, pinned: prefs.pinned.includes(id) ? prefs.pinned.filter((item) => item !== id) : [...prefs.pinned, id] }); }
  return <div className="relative"><span className="mb-2 block text-sm text-slate-300">{label}</span><button type="button" disabled={disabled || !genomes.length} onClick={() => setOpen(true)} className="flex h-11 w-full items-center justify-between gap-3 rounded-lg border border-slate-700 bg-slate-900/80 px-3 text-left text-sm text-slate-100 outline-none transition hover:border-[#2dd4bf] focus:border-[#2dd4bf] disabled:opacity-50"><span className="min-w-0 truncate">{selected ? `#${selected.id} · ${selected.name || role(selected.role)}` : "選擇參數"}</span><Search className="h-4 w-4 shrink-0 text-slate-400"/></button>{open ? <div className="fixed inset-0 z-50 flex items-start justify-center bg-slate-950/75 p-4 pt-[8vh]" role="dialog" aria-modal="true" onMouseDown={() => setOpen(false)}><div className="max-h-[84vh] w-full max-w-3xl overflow-hidden rounded-xl border border-white/10 bg-slate-950 shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><div className="font-semibold text-slate-100">選擇參數</div><div className="mt-1 text-xs text-slate-500">搜尋名稱、編號、標的或週期；常用項目可釘選。</div></div><Button size="sm" variant="ghost" icon={X} onClick={() => setOpen(false)}>關閉</Button></div><div className="border-b border-white/10 p-4"><label className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/[.03] px-3"><Search className="h-4 w-4 text-slate-500"/><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="例如：SOXL、已採用、#42" className="h-10 min-w-0 flex-1 bg-transparent text-sm text-slate-100 outline-none placeholder:text-slate-600"/></label></div><div className="max-h-[56vh] overflow-y-auto p-3"><Rows title="已釘選" items={pinned} selected={value} prefs={prefs} choose={choose} toggle={toggle}/><Rows title="最近使用" items={recent} selected={value} prefs={prefs} choose={choose} toggle={toggle}/><Rows title="所有結果" items={others} selected={value} prefs={prefs} choose={choose} toggle={toggle} empty={matches.length === 0 ? "沒有符合條件的參數。" : undefined}/></div></div></div> : null}</div>;
}

function Rows({ title, items, selected, prefs, choose, toggle, empty }: { title: string; items: GenomeRecord[]; selected: number; prefs: Preferences; choose: (item: GenomeRecord) => void; toggle: (id: number) => void; empty?: string }) { if (!items.length && !empty) return null; return <section className="mb-4 last:mb-0"><div className="mb-1.5 px-2 text-xs font-semibold text-slate-400">{title}</div>{items.length ? <div className="space-y-1">{items.map((item) => <div key={item.id} className={`flex items-center gap-2 rounded-lg border p-2 ${item.id === selected ? "border-teal-400/40 bg-teal-400/10" : "border-transparent hover:bg-white/[.04]"}`}><button type="button" className="min-w-0 flex-1 text-left" onClick={() => choose(item)}><span className="flex items-center gap-2 text-sm text-slate-200">#{item.id} · {item.name || role(item.role)}{item.id === selected ? <Check className="h-4 w-4 text-teal-300"/> : null}</span><span className="mt-0.5 block truncate text-xs text-slate-500">{role(item.role)} · {item.instrument_id ?? "未指定標的"} · {item.interval ?? "未指定週期"}</span></button><button type="button" className={`rounded p-2 ${prefs.pinned.includes(item.id) ? "text-amber-300" : "text-slate-600 hover:text-slate-300"}`} onClick={() => toggle(item.id)} aria-label={prefs.pinned.includes(item.id) ? "取消釘選" : "釘選"}><Pin className="h-4 w-4" fill={prefs.pinned.includes(item.id) ? "currentColor" : "none"}/></button></div>)}</div> : <div className="rounded-lg border border-dashed border-white/10 px-3 py-5 text-sm text-slate-500">{empty}</div>}</section>; }
