import { useMemo, useState } from "react";
import { Check, Search, X } from "lucide-react";
import { Button } from "./Button";

export type SearchableOption = { value: string; label: string; detail?: string };
export function SearchablePicker({ label, options, value, onChange, disabled }: { label: string; options: SearchableOption[]; value: string; onChange: (value: string) => void; disabled?: boolean }) {
  const [open, setOpen] = useState(false), [query, setQuery] = useState("");
  const selected = options.find((item) => item.value === value);
  const matches = useMemo(() => { const text = query.trim().toLowerCase(); return options.filter((item) => !text || `${item.label} ${item.detail ?? ""}`.toLowerCase().includes(text)); }, [options, query]);
  function choose(next: string) { onChange(next); setOpen(false); setQuery(""); }
  return <div className="relative"><span className="mb-2 block text-sm text-slate-300">{label}</span><button type="button" disabled={disabled || !options.length} onClick={() => setOpen(true)} className="flex h-11 w-full items-center justify-between gap-3 rounded-lg border border-slate-700 bg-slate-900/80 px-3 text-left text-sm text-slate-100 outline-none transition hover:border-[#2dd4bf] focus:border-[#2dd4bf] disabled:opacity-50"><span className="min-w-0 truncate">{selected?.label ?? "選擇項目"}</span><Search className="h-4 w-4 shrink-0 text-slate-400"/></button>{open ? <div className="fixed inset-0 z-50 flex items-start justify-center bg-slate-950/75 p-4 pt-[8vh]" role="dialog" aria-modal="true" onMouseDown={() => setOpen(false)}><div className="max-h-[84vh] w-full max-w-2xl overflow-hidden rounded-xl border border-white/10 bg-slate-950 shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><div className="font-semibold text-slate-100">選擇{label}</div><div className="mt-1 text-xs text-slate-500">可依名稱、代號或說明搜尋。</div></div><Button size="sm" variant="ghost" icon={X} onClick={() => setOpen(false)}>關閉</Button></div><div className="border-b border-white/10 p-4"><label className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/[.03] px-3"><Search className="h-4 w-4 text-slate-500"/><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="輸入關鍵字搜尋" className="h-10 min-w-0 flex-1 bg-transparent text-sm text-slate-100 outline-none placeholder:text-slate-600"/></label></div><div className="max-h-[56vh] overflow-y-auto p-3">{matches.length ? <div className="space-y-1">{matches.map((item) => <button key={item.value} type="button" onClick={() => choose(item.value)} className={`flex w-full items-center gap-3 rounded-lg border p-3 text-left ${item.value === value ? "border-teal-400/40 bg-teal-400/10" : "border-transparent hover:bg-white/[.04]"}`}><span className="min-w-0 flex-1"><span className="block truncate text-sm text-slate-200">{item.label}</span>{item.detail ? <span className="mt-1 block truncate text-xs text-slate-500">{item.detail}</span> : null}</span>{item.value === value ? <Check className="h-4 w-4 shrink-0 text-teal-300"/> : null}</button>)}</div> : <div className="rounded-lg border border-dashed border-white/10 px-3 py-5 text-sm text-slate-500">沒有符合的項目。</div>}</div></div></div> : null}</div>;
}
