import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BrainCircuit, Play, RefreshCw, Square, Workflow } from "lucide-react";
import { marketDataApi } from "../../shared/services/marketData";
import { trendGeometryApi, type CreateGeometryStudy } from "../../shared/services/trendGeometry";
import { computeTasksApi, type ComputeTask } from "../../shared/services/computeTasks";
import { datasetStartDate } from "../../shared/lib/datasetDates";
import { Button } from "../../shared/ui/Button";
import { Card, CardDescription, CardHeader, CardTitle } from "../../shared/ui/Card";
import { ComputePlanSummary, ComputeProgress, ComputeStatusBadge } from "../computetasks/ComputeTaskComponents";
import { SearchablePicker } from "../../shared/ui/SearchablePicker";

const inputClass = "min-h-10 w-full rounded-lg border border-white/10 bg-slate-950/70 px-3 text-sm text-slate-200 outline-none focus:border-cyan-400/50";
const activeStatuses = new Set(["queued", "running", "partial"]);
const dayStart = (value: string) => value ? new Date(`${value}T00:00:00`).getTime() : 0;
const dayEnd = (value: string) => value ? new Date(`${value}T23:59:59.999`).getTime() : 0;
const dateValue = (date: Date) => date.toISOString().slice(0, 10);

export function TrendGeometryPage() {
  const queryClient = useQueryClient();
  const instrumentsQuery = useQuery({ queryKey: ["market-data-instruments"], queryFn: marketDataApi.instruments });
  const studiesQuery = useQuery({ queryKey: ["trend-geometry-studies"], queryFn: () => trendGeometryApi.list(80) });
  const artifactsQuery = useQuery({ queryKey: ["trend-geometry-artifacts"], queryFn: () => trendGeometryApi.artifacts() });
  const instruments = instrumentsQuery.data?.instruments ?? [];
  const [instrumentId, setInstrumentId] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState(() => dateValue(new Date(Date.now() - 86400000)));
  const [lookbacksText, setLookbacksText] = useState("5,10,20,40,60,120,250,500");
  const [folds, setFolds] = useState(4);
  const [minimumTrain, setMinimumTrain] = useState(120);
  const [selectedID, setSelectedID] = useState(0);
  const [taskID, setTaskID] = useState(0);
  const [previewSignature, setPreviewSignature] = useState("");
  const [confirm, setConfirm] = useState(false);
  const selected = instruments.find((item) => item.id === instrumentId);
  const start = datasetStartDate(selected, "1d");
  useEffect(() => { if (!instrumentId && instruments.length) setInstrumentId(instruments.find((item) => item.supported_intervals.includes("1d"))?.id ?? instruments[0].id); }, [instrumentId, instruments]);
  useEffect(() => { if (start) setStartDate(start); }, [start]);
  const lookbacks = useMemo(() => [...new Set(lookbacksText.split(",").map(Number).filter((value) => [5, 10, 20, 40, 60, 120, 250, 500].includes(value)))].sort((a, b) => a - b), [lookbacksText]);
  const request: CreateGeometryStudy = { name: `走勢幾何預測 ${selected?.display_name ?? selected?.symbol ?? "市場"}`, instrument_id: instrumentId, data_source: selected?.data_source ?? "", symbol: selected?.symbol ?? "", interval: "1d", train_start_time_ms: dayStart(startDate), train_end_time_ms: dayEnd(endDate), lookbacks, folds, minimum_train: minimumTrain, confirm_soft_limit: confirm };
  const signature = JSON.stringify({ ...request, confirm_soft_limit: false });
  const valid = !!selected && lookbacks.length > 0 && folds >= 2 && minimumTrain >= 8 && request.train_end_time_ms > request.train_start_time_ms;
  const preview = useMutation({ mutationFn: (input: CreateGeometryStudy) => trendGeometryApi.preview({ ...input, confirm_soft_limit: false }), onSuccess: (_, input) => { setPreviewSignature(JSON.stringify({ ...input, confirm_soft_limit: false })); setConfirm(false); } });
  const create = useMutation({ mutationFn: () => trendGeometryApi.create(request), onSuccess: (value) => { setSelectedID(value.study.id); setTaskID(value.task?.id ?? value.study.compute_task_id ?? 0); queryClient.invalidateQueries({ queryKey: ["trend-geometry-studies"] }); } });
  const study = useQuery({ queryKey: ["trend-geometry-study", selectedID], queryFn: () => trendGeometryApi.get(selectedID), enabled: selectedID > 0 });
  const task = useQuery({ queryKey: ["compute-task", taskID], queryFn: () => computeTasksApi.get(taskID), enabled: taskID > 0, refetchInterval: (query) => activeStatuses.has((query.state.data as ComputeTask | undefined)?.status ?? "") ? 1200 : false });
  useEffect(() => { const id = study.data?.compute_task_id ?? 0; if (id && id !== taskID) setTaskID(id); }, [study.data?.compute_task_id, taskID]);
  const action = useMutation({ mutationFn: ({ kind, id }: { kind: "start" | "cancel"; id: number }) => computeTasksApi[kind](id), onSuccess: (value) => queryClient.setQueryData(["compute-task", value.id], value) });
  return <section className="space-y-5">
    <header><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-100"><BrainCircuit className="h-6 w-6 text-cyan-300" />走勢幾何預測</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">獨立的走勢幾何模型研究頁面，訓練 1 日與 20 日目標，並保存候選模型、預測分布、資料集雜湊與相容 artifact。此頁不改動既有 P09 或 Beta 控制。</p></header>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,.8fr)]">
      <Card><CardHeader><CardTitle>建立研究任務</CardTitle><CardDescription>使用相同 purged expanding walk-forward 折疊比較 lookback 與區域數。</CardDescription></CardHeader><div className="grid gap-4 md:grid-cols-2"><SearchablePicker label="市場資料" value={instrumentId} onChange={setInstrumentId} options={instruments.filter((item) => item.supported_intervals.includes("1d")).map((item) => ({ value: item.id, label: item.display_name, detail: `${item.symbol} · ${item.market ?? "市場"}` }))}/><Field label="折疊數"><input className={inputClass} type="number" min={2} value={folds} onChange={(event) => setFolds(Number(event.target.value))}/></Field><Field label="開始日期"><input className={inputClass} type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)}/></Field><Field label="結束日期"><input className={inputClass} type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)}/></Field><Field label="最小訓練樣本"><input className={inputClass} type="number" min={8} value={minimumTrain} onChange={(event) => setMinimumTrain(Number(event.target.value))}/></Field><div className="md:col-span-2"><Field label="候選 lookback"><input className={inputClass} value={lookbacksText} onChange={(event) => setLookbacksText(event.target.value)}/><span className="text-xs text-slate-500">可用值：5, 10, 20, 40, 60, 120, 250, 500 根 K 線</span></Field></div></div><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" disabled={!valid || preview.isPending} onClick={() => preview.mutate(request)}><RefreshCw className="mr-2 h-4 w-4"/>預覽</Button><Button disabled={!valid || previewSignature !== signature || (preview.data?.requires_confirmation && !confirm) || create.isPending} onClick={() => create.mutate()}><Workflow className="mr-2 h-4 w-4"/>建立任務</Button></div>{preview.data && <div className="mt-4"><ComputePlanSummary preview={preview.data}/>{preview.data.requires_confirmation && <label className="mt-3 flex items-start gap-2 rounded-lg border border-amber-400/20 bg-amber-400/10 p-3 text-sm text-amber-100"><input className="mt-1" type="checkbox" checked={confirm} onChange={(event) => setConfirm(event.target.checked)}/><span>此次研究超過軟性資源上限，確認建立。</span></label>}</div>}{(preview.error || create.error) && <p className="mt-3 text-sm text-rose-300">{String((preview.error || create.error)?.message)}</p>}</Card>
      <Card><CardHeader><CardTitle>研究清單</CardTitle><CardDescription>選取已建立的幾何研究查看任務與結果。</CardDescription></CardHeader><div className="max-h-[520px] space-y-2 overflow-auto">{(studiesQuery.data ?? []).map((item) => <button key={item.id} className={`w-full rounded-lg border p-3 text-left ${selectedID === item.id ? "border-cyan-400/40 bg-cyan-400/5" : "border-white/[0.06] bg-white/[0.02]"}`} onClick={() => { setSelectedID(item.id); setTaskID(item.compute_task_id ?? 0); }}><div className="flex items-center justify-between"><span className="text-sm font-medium text-slate-200">{item.name}</span><span className="text-xs text-slate-500">#{item.id}</span></div><div className="mt-1 text-xs text-slate-500">{item.status} · {item.dataset_hash.slice(0, 10)}…</div></button>)}{studiesQuery.data?.length === 0 && <p className="text-sm text-slate-500">尚無研究。</p>}</div></Card>
    </div>
    {task.data && <Card><CardHeader><CardTitle>計算任務</CardTitle><CardDescription>{task.data.title}</CardDescription><ComputeStatusBadge status={task.data.status}/></CardHeader><ComputeProgress task={task.data}/><div className="mt-4 flex gap-2">{task.data.status === "planned" && <Button onClick={() => action.mutate({ kind: "start", id: task.data.id })}><Play className="mr-2 h-4 w-4"/>開始</Button>}{activeStatuses.has(task.data.status) && <Button variant="danger" onClick={() => action.mutate({ kind: "cancel", id: task.data.id })}><Square className="mr-2 h-4 w-4"/>取消</Button>}</div></Card>}
    {study.data?.artifact_set_hash && <Card><CardHeader><CardTitle>模型 artifact</CardTitle><CardDescription>完成後的模型含候選 walk-forward 報告與內容雜湊。</CardDescription></CardHeader><div className="grid gap-3 md:grid-cols-3"><Hash label="artifact 集合" value={study.data.artifact_set_hash}/><Hash label="資料集" value={study.data.dataset_hash}/><Hash label="設定" value={study.data.setting_hash}/></div><ResultTable artifacts={study.data.artifacts ?? []}/></Card>}
    {study.data?.predictions && <Card><CardHeader><CardTitle>預測分布</CardTitle><CardDescription>每筆決策日預測均保存內容雜湊；目標窗口以決策日作為連接錨點。</CardDescription></CardHeader><PredictionTable title="1 日" rows={study.data.predictions.one_day.filter((item) => item.available).slice(-10)}/><PredictionTable title="20 日" rows={study.data.predictions.twenty_day.filter((item) => item.available).slice(-10)}/></Card>}
    {artifactsQuery.data && artifactsQuery.data.length > 0 && <Card><CardHeader><CardTitle>可相容的已完成 artifact</CardTitle><CardDescription>依市場、資料集、週期與目標期限篩選後可供研究端選取。</CardDescription></CardHeader><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="p-2">研究</th><th className="p-2">期限</th><th className="p-2">lookback</th><th className="p-2">資料集</th><th className="p-2">內容雜湊</th></tr></thead><tbody>{artifactsQuery.data.slice(0, 20).map((artifact) => <tr key={artifact.artifact_id} className="border-t border-white/[0.05]"><td className="p-2 text-slate-300">{artifact.study_name}</td><td className="p-2 text-slate-300">{artifact.horizon} 日</td><td className="p-2 text-slate-300">{artifact.lookback}</td><td className="p-2 text-slate-400">{artifact.dataset_hash.slice(0, 10)}…</td><td className="p-2 text-slate-400">{artifact.content_hash.slice(0, 10)}…</td></tr>)}</tbody></table></div></Card>}
  </section>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-1.5"><span className="text-xs font-medium text-slate-400">{label}</span>{children}</label>; }
function Hash({ label, value }: { label: string; value?: string }) { return <div className="rounded-lg border border-white/[0.05] bg-white/[0.025] p-3"><div className="text-xs text-slate-500">{label}</div><code className="mt-1 block text-xs text-slate-300">{value ? `${value.slice(0, 12)}…${value.slice(-8)}` : "尚未產生"}</code></div>; }
function ResultTable({ artifacts }: { artifacts: NonNullable<import("../../shared/services/trendGeometry").GeometryStudy["artifacts"]> }) { return <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="p-2">期限</th><th className="p-2">lookback</th><th className="p-2">區域</th><th className="p-2">Joint NLL</th><th className="p-2">purge</th></tr></thead><tbody>{artifacts.map((artifact) => <tr key={artifact.id} className="border-t border-white/[0.05]"><td className="p-2">{artifact.horizon} 日</td><td className="p-2">{artifact.lookback}</td><td className="p-2">{artifact.report.regions}</td><td className="p-2">{artifact.report.joint_nll.toFixed(5)}</td><td className="p-2">{artifact.report.purge}</td></tr>)}</tbody></table></div>; }
function PredictionTable({ title, rows }: { title: string; rows: Array<{ index: number; content_hash?: string; distribution?: { regions: Array<{ probability: number; area_center: number; slope_center: number }> } }> }) { return <div className="mt-4 overflow-x-auto"><div className="mb-2 text-sm font-medium text-slate-300">{title}</div><table className="w-full text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="p-2">索引</th><th className="p-2">區域機率</th><th className="p-2">面積中心</th><th className="p-2">斜率中心</th><th className="p-2">內容雜湊</th></tr></thead><tbody>{rows.map((row) => <tr key={row.index} className="border-t border-white/[0.05]"><td className="p-2">{row.index}</td><td className="p-2">{row.distribution?.regions.map((region) => `${(region.probability * 100).toFixed(1)}%`).join(" / ")}</td><td className="p-2">{row.distribution?.regions.map((region) => region.area_center.toFixed(4)).join(" / ")}</td><td className="p-2">{row.distribution?.regions.map((region) => region.slope_center.toFixed(4)).join(" / ")}</td><td className="p-2 text-xs">{row.content_hash?.slice(0, 10)}…</td></tr>)}</tbody></table></div>; }
